backend:
  name: git-gateway
  branch: main # Cambia a la rama que usas en tu repositorio

media_folder: "images/uploads" # Carpeta donde se guardarán las imágenes que subas
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    folder: "content/pages" # Carpeta donde estarán los archivos que podrás editar
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
